ARG SNAPSHOT=""
FROM strongboxci/opensuse:base$SNAPSHOT

ENV JDK_VERSION_STRING=jdk-11.0.9.1+1 \
    JDK_CHECKSUM=e388fd7f3f2503856d0b04fde6e151cbaa91a1df3bcebf1deddfc3729d677ca3

ENV JAVA_HOME="/java/${JDK_VERSION_STRING}"
ENV PATH $JAVA_HOME/bin:$PATH

ENV JMETER_VERSION=5.3 \
    JMETER_CHECKSUM=922195b901358c2bf0d454e4b19fa2b45f072f0e0327b06c229935c2de0b785b641e7a58ceaa4682cf3643aeed4915256ae003b487b0c9a2144bb33c2b12e28e

COPY common-scripts /scripts

USER root

RUN set -ex \
 && /scripts/setup-jdk.sh \
 && /scripts/setup-jmeter.sh \
 && rm -rf /tmp/* /scripts

USER jenkins

CMD echo "" && java -version && echo "" && /bin/bash
