FROM mono:5.20 as builder

ENV CHOCO_VERSION=773b1852d9de9ab628598a9b29fe7d0f9d04f668

COPY common-scripts /scripts

RUN set -ex \
 && echo "Building chocolatey..." \
 && /bin/bash /scripts/setup-choco.sh build

ARG SNAPSHOT=""
FROM strongboxci/alpine:jdk8-mvn3.6-mono5-nuget3.4$SNAPSHOT

ENV ChocolateyInstall=/opt/chocolatey

COPY common-scripts /scripts
COPY --from=builder /usr/src/choco/build_output/chocolatey $ChocolateyInstall

USER root

RUN set -ex \
 && echo "Setting up chocolatey..." \
 && /bin/bash /scripts/setup-choco.sh setupScript \
 && rm -rf /tmp/* /scripts

USER jenkins

CMD echo "" && mono --version && echo "" && echo -n "Choco: " && choco --version && echo "" && mvn --version && echo "" && /bin/bash
