ARG SNAPSHOT=""
FROM strongboxci/alpine:jdk8-mvn3.6$SNAPSHOT

USER root

RUN set -ex \
 && apk add --no-cache python3 \
 && apk add --no-cache --virtual twine-deps libffi gcc musl-dev python3-dev libffi-dev openssl-dev \
 && ln -s /usr/bin/python3 /usr/bin/python \
 && rm -rf /tmp/*

# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
ENV PYTHON_PIP_VERSION 19.3.1
# https://github.com/pypa/get-pip
ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/ffe826207a010164265d9cc807978e3604d18ca0/get-pip.py
ENV PYTHON_GET_PIP_SHA256 b86f36cc4345ae87bfd4f10ef6b2dbfa7a872fbff70608a1e43944d283fd0eee

RUN set -ex; \
    \
    mkdir -p $HOME/.cache/pip; \
    chown -R $USER_ID.$GROUP_ID $HOME; \
    chmod -R 755 $HOME; \
    curl -o get-pip.py "$PYTHON_GET_PIP_URL"; \
    echo "$PYTHON_GET_PIP_SHA256 *get-pip.py" | sha256sum -c -; \
    \
    python get-pip.py \
	--disable-pip-version-check \
	--no-cache-dir \
	"pip==$PYTHON_PIP_VERSION" \
    ; \
    pip --version; \
    \
    find /usr/local -depth \
	\( \
	    \( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
	    -o \
	    \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
	\) -exec rm -rf '{}' +; \
    rm -f get-pip.py

RUN set -ex \
 && pip install twine \
 && echo "Testing python installation" > /dev/null \
 && python --version \
 && python3 --version \
 && echo "Testing pip installation" > /dev/null \
 && pip --version \
 && echo "Test twine installation" > /dev/null \
 && twine --version \
 && apk del twine-deps \
 && twine --version

USER jenkins

CMD echo "" && python3 --version && echo "" && pip --version && echo "" && twine --version && echo "" && /bin/bash