ARG SNAPSHOT=""
FROM strongboxci/alpine:jdk8-mvn3.6$SNAPSHOT

USER root

RUN set -ex \
 && apk add --no-cache python3 \
 && apk add --no-cache --virtual twine-deps libffi gcc musl-dev python3-dev libffi-dev openssl-dev \
 && ln -s /usr/bin/python3 /usr/bin/python \
 && rm -rf /tmp/*

# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
# https://github.com/pypa/get-pip
ENV PYTHON_PIP_VERSION 19.3.1

# We are using cryptography < 3.4 for pyp == 19.3 or it will fail to install.
RUN set -ex; \
    \
    mkdir -p $HOME/.cache/pip; \
    chown -R $USER_ID.$GROUP_ID $HOME; \
    chmod -R 755 $HOME; \
    curl -o get-pip.py -L "https://bootstrap.pypa.io/get-pip.py"; \
    python get-pip.py --disable-pip-version-check --no-cache-dir "pip==$PYTHON_PIP_VERSION" "cryptography < 3.4"; \
    pip --version; \
    \
    find /usr/local -depth \
	\( \
	    \( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
	    -o \
	    \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
	\) -exec rm -rf '{}' +; \
    rm -f get-pip.py; \
    mkdir -p `dirname $(pip --version | cut -f 4 -d " ")`; \
    chown -R $USER_ID.$GROUP_ID $(dirname $(pip --version | cut -f 4 -d " "))

RUN set -ex \
 && pip install twine \
 && echo "Testing python installation" > /dev/null \
 && python --version \
 && python3 --version \
 && echo "Testing pip installation" > /dev/null \
 && pip --version \
 && echo "Test twine installation" > /dev/null \
 && twine --version \
 && apk del twine-deps \
 && rm -rf /tmp/*

USER jenkins

CMD printf '--- Image info ---\n%s \n%s \n%s\n------------------\n' "+ $(python3 --version | xargs)" "+ $(pip --version | xargs)" "+ $(twine --version | xargs)" && /bin/bash
