ARG SNAPSHOT=""
FROM strongboxci/alpine:jdk17-mvn3.6-mono5$SNAPSHOT

# setup-nuget.sh
ENV NUGET_VERSION=3.4.4
ENV NUGET_PATH=/usr/local/bin/nuget-${NUGET_VERSION}.exe

# S-W-I-T expects these environment variables to be set.
ENV NUGET_VERSION=$NUGET_VERSION
ENV NUGET_PATH=$NUGET_PATH
ENV NUGET_EXEC="mono ${NUGET_PATH}"

COPY common-scripts /scripts

USER root

RUN set -x \
 && /bin/bash /scripts/setup-nuget.sh \
 && echo "Clean..." > /dev/null \
 && rm -rf /tmp/* /scripts

USER jenkins

CMD printf '--- Image details ---\n%s \n%s \n%s \n------------------\n' "$(mvn --version)" "$(mono $NUGET_PATH | head -n 1)" "$(mono --version)" && /bin/bash
