ARG SNAPSHOT=""
FROM strongboxci/alpine:jdk17-mvn3.6$SNAPSHOT

ENV SBT_VERSION=1.3.13
ENV SBT_HOME="/java/sbt-${SBT_VERSION}"

COPY common-scripts /scripts

USER root

RUN set -x \
 && /scripts/setup-sbt.sh \
 && rm -rf /tmp/* /scripts

USER jenkins
