ARG SNAPSHOT=""
FROM strongboxci/ubuntu:base$SNAPSHOT

ENV JDK_VERSION_STRING=jdk-11.0.9.1+1 \
    JDK_CHECKSUM=e388fd7f3f2503856d0b04fde6e151cbaa91a1df3bcebf1deddfc3729d677ca3

ENV JAVA_HOME="/java/jdk"
ENV PATH $JAVA_HOME/bin:$PATH

ENV JMETER_VERSION=5.4.3 \
    JMETER_CHECKSUM=e88802cc0dfcd6a2c8554911ae4574d7cfafcc8c6be6ade810b4677b7351831b0680d81cf2b0fb5bb4b9b3cf437528a044d7da74214a1bee351b273dbb53e439

COPY common-scripts /scripts

USER root

RUN set -ex \
 && /scripts/setup-jdk.sh \
 && /scripts/setup-jmeter.sh \
 && rm -rf /tmp/* /scripts

USER jenkins

CMD echo "" && java -version && echo "" && /bin/bash
