ARG SNAPSHOT=""
FROM strongboxci/ubuntu:jdk11$SNAPSHOT

ENV MVN_MAJOR_VERSION=3
ENV MVN_VERSION=3.6.3
ENV MVN_CHECKSUM=c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0
ENV M2_HOME="/java/mvn-${MVN_VERSION}"

COPY common-scripts /scripts

USER root

RUN set -x \
 && /scripts/setup-mvn.sh \
 && rm -rf /tmp/* /scripts

USER jenkins

CMD echo "" && mvn --version && echo "" && /bin/bash

