ARG SNAPSHOT=""
FROM strongboxci/debian:base$SNAPSHOT

ENV JDK_VERSION_STRING=jdk-17.0.2+8 \
    JDK_CHECKSUM=288f34e3ba8a4838605636485d0365ce23e57d5f2f68997ac4c2e4c01967cd48

ENV JAVA_HOME="/java/jdk"
ENV PATH $JAVA_HOME/bin:$PATH

ENV JMETER_VERSION=5.4.3 \
    JMETER_CHECKSUM=e88802cc0dfcd6a2c8554911ae4574d7cfafcc8c6be6ade810b4677b7351831b0680d81cf2b0fb5bb4b9b3cf437528a044d7da74214a1bee351b273dbb53e439

COPY common-scripts /scripts

USER root

RUN set -ex \
 && /scripts/setup-jdk.sh \
 && /scripts/setup-jmeter.sh \
 && rm -rf /tmp/* /scripts

USER jenkins

CMD echo "" && java -version && echo "" && /bin/bash
