ARG SNAPSHOT=""
FROM strongboxci/alpine:jdk11-mvn3.6$SNAPSHOT

ENV GRADLE_VERSION=5.6
ENV GRADLE_HOME="/java/gradle-${GRADLE_VERSION}"

COPY common-scripts /scripts

USER root

RUN set -ex \
 && /bin/bash /scripts/setup-gradle.sh \
 && rm -rf /tmp/* /scripts

USER jenkins

CMD echo "" && gradle --version && echo "" && /bin/bash

