FROM mono:5.20 as builder

ENV CHOCO_VERSION=9bb4246354188e4205b5dbcae6f8638351eccb13

COPY common-scripts /scripts

RUN set -ex \
 && echo "Building chocolatey..." \
 && /bin/bash /scripts/setup-choco.sh build

ARG SNAPSHOT=""
FROM strongboxci/alpine:jdk11-mvn3.6-mono5-nuget5.7$SNAPSHOT

ENV ChocolateyInstall=/opt/chocolatey

COPY common-scripts /scripts
COPY --from=builder /usr/src/choco/build_output/chocolatey $ChocolateyInstall

USER root

RUN set -ex \
 && echo "Setting up chocolatey..." \
 && /bin/bash /scripts/setup-choco.sh setupScript \
 && rm -rf /tmp/* /scripts

USER jenkins

CMD echo "" && mono --version && echo "" && echo -n "Choco: " && choco --version && echo "" && mvn --version && echo "" && /bin/bash
