ARG SNAPSHOT=""
FROM strongboxci/alpine:jdk11$SNAPSHOT

ENV MVN_MAJOR_VERSION=3
ENV MVN_VERSION=3.6.2
ENV M2_HOME="/java/mvn-${MVN_VERSION}"

COPY common-scripts /scripts

USER root

RUN set -x \
 && /scripts/setup-mvn.sh \
 && rm -rf /tmp/* /scripts

USER jenkins

CMD echo "" && mvn --version && echo "" && /bin/bash

